### PR TITLE
Fixed a spelling mistake

### PR DESCRIPTION
**Pull request by TNorbury**
### Pull Request Checklist
Please review the [Contribution Guidelines](https://github.com/tektronix/syphon/blob/master/CONTRIBUTING.md) before submitting.

- [X] Pulling from a topic/feature/bugfix branch (right side).
- [X] Pulling against the `canary` branch (left side).
- [X] Code passes linting.
- [X] Code passes unit tests.
- [X] Code coverage is the same or better.
- [X] You have previously submitted a Contributor License Agreement or have contacted a maintainer to request one. (I work at Tektronix, so I don't think I need to submit one of these)

### Description
Fixed a small spelling mistake in the name_map function doc

### CODE REVIEW

**Comment by zkoppert** [comment]
Hey @TNorbury, Can you confirm that you have your tektronix email in your github account?

**Comment by TNorbury** [comment]
@zkoppert 
Yeah, my email is there. Though I have my emails set to private, do I need to change that and then set my Tek email as my "public" one?

**Comment by zkoppert** [comment]
> @zkoppert
> Yeah, my email is there. Though I have my emails set to private, do I need to change that and then set my Tek email as my "public" one?

I don't think so. I will get @nlynchjo to take a look at the requirements for the CLA bot to work. Hold tight. Might be until Monday.

**Comment by TNorbury** [comment]
Per the changes from #18 my original change was made obsolete, however I made another change that I feel like it similar enough in scope and so I'm just going to make it part of this PR

**Comment by ethall** [comment]
Thanks for the fix, @TNorbury!

Unfortunately you submitted your pull request a few minutes before I created PR #18, which reworded the documentation you corrected.

If you see any other typos or opportunities to extend the documentation, then don't hesitate to submit another PR. (#18 finalizes the module structure, so additional PR's won't be as dangerous to make.)

**Comment by ethall** [comment]
Looks like I spoke too soon.

**Pull request merged**
